name: hukum_pro
description: HukumPro

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter-json:
  enable: true

dependencies:
  bloc: "7.0.0"
  equatable: "2.0.3"
  freezed_annotation: "0.14.2"
  firebase_core: "1.3.0"
  firebase_database: "7.1.1"
  firebase_storage: "8.1.3"
  flinq: "2.0.2"
  flutter:
    sdk: flutter
  flutter_bloc: "7.0.1"
  hive: "2.0.4"
  hive_flutter: "1.1.0"
  json_serializable: "4.1.3"
  kiwi: "3.0.0"
  objectbox: "1.0.0"
  objectbox_flutter_libs: "1.0.0"
  path_provider: "2.0.2"
  shared_preferences: "2.0.6"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  bloc_test: "8.0.2"
  test: "1.16.8"
  build_runner: "2.0.4"
  freezed: "0.14.2"
  hive_generator: "1.1.0"
  kiwi_generator: "3.0.0"
  mockito: "5.0.10"
  objectbox_generator: "1.0.0"
  remove_from_coverage: "2.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - res/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: Montserrat
      fonts:
        - asset: res/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: res/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: res/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: res/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: res/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: res/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: res/fonts/Montserrat-Italic.ttf
          weight: 400
          style: italic
        - asset: res/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: res/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: res/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: res/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: res/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: res/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: res/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: res/fonts/Montserrat-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: res/fonts/Catamaran-Black.ttf
          weight: 900
        - asset: res/fonts/Catamaran-Bold.ttf
          weight: 700
        - asset: res/fonts/Catamaran-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/Catamaran-ExtraLight.ttf
          weight: 200
        - asset: res/fonts/Catamaran-Light.ttf
          weight: 300
        - asset: res/fonts/Catamaran-Medium.ttf
          weight: 500
        - asset: res/fonts/Catamaran-Regular.ttf
          weight: 400
        - asset: res/fonts/Catamaran-SemiBold.ttf
          weight: 600
        - asset: res/fonts/Catamaran-Thin.ttf
          weight: 100
        - asset: res/fonts/Khula-Bold.ttf
          weight: 700
        - asset: res/fonts/Khula-ExtraBold.ttf
          weight: 800
        - asset: res/fonts/Khula-Light.ttf
          weight: 300
        - asset: res/fonts/Khula-Regular.ttf
          weight: 400
        - asset: res/fonts/Khula-SemiBold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
targets:
  $default:
    builders:
      kiwi:
